"""empty message

Revision ID: 4ee7b2b69e92
Revises: 67efb28509e7
Create Date: 2021-03-25 20:33:39.727312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ee7b2b69e92'
down_revision = '67efb28509e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('contact', sa.String(length=11), nullable=True))
    op.drop_column('booking', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('phone', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('booking', 'contact')
    # ### end Alembic commands ###
