"""empty message

Revision ID: 90ef326132a3
Revises: ecbacce9f867
Create Date: 2021-03-24 21:55:57.663504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90ef326132a3'
down_revision = 'ecbacce9f867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_profiles', sa.Column('position', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_profiles', 'position')
    # ### end Alembic commands ###
