"""empty message

Revision ID: 987778d37e9d
Revises: 90ef326132a3
Create Date: 2021-03-24 22:38:38.758115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987778d37e9d'
down_revision = '90ef326132a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cfname', sa.String(length=40), nullable=True),
    sa.Column('clname', sa.String(length=40), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    # ### end Alembic commands ###
