"""empty message

Revision ID: bef678c7ebfd
Revises: 987778d37e9d
Create Date: 2021-03-24 22:56:46.758174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef678c7ebfd'
down_revision = '987778d37e9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employee_profiles_username_key', 'employee_profiles', type_='unique')
    op.drop_column('employee_profiles', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_profiles', sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.create_unique_constraint('employee_profiles_username_key', 'employee_profiles', ['username'])
    # ### end Alembic commands ###
